package carsrental;
// Generated 06.05.2017 22:37:10 by Hibernate Tools 4.3.1



/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private String carid;
     private String name;
     private String vendor;
     private String type;

    public Cars() {
    }

	
    public Cars(String carid) {
        this.carid = carid;
    }
    public Cars(String carid, String name, String vendor, String type) {
       this.carid = carid;
       this.name = name;
       this.vendor = vendor;
       this.type = type;
    }
   
    public String getCarid() {
        return this.carid;
    }
    
    public void setCarid(String carid) {
        this.carid = carid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


